version: '3.8'

services:
  spring-app:
    container_name: picplz-dev-server
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      REDIS_PASSWORD: picplz2025!!
    networks:
      - default

volumes:
  redis-data:

networks:
  default:
    driver: host