version: '3.8'

services:
  spring-app:
    container_name: spring-app
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:mysql://picplz-db.cveay68wqy5c.ap-northeast-2.rds.amazonaws.com:3306/picplz
      SPRING_DATASOURCE_USERNAME: picplz
      SPRING_DATASOURCE_PASSWORD: vlrvmfwm18!
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      REDIS_PASSWORD: picplz

volumes:
  mysql-data:
  redis-data:
