spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 0551bd129e9d85f97d7209fa25ba982e   # 앱 키 - REST API 키
            client-secret: zgK9de8rO3xmO8HKXz4ZgsEciHlTlIMs   # 보안 - Client Secret  키
            redirect-uri: http://localhost:8080/api/v1/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
