spring:
  profiles:
    include: jwt, oauth
    active : dev
    group:
      local: local
      prod: prod
      dev: dev
  application:
    name: picplz

server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    org:
      hibernate:
        SQL: debug
    web: debug
    com: INFO
    root: INFO

springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/v1/**

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://mysql-db:3306/picplz?autoReconnect=true&useUnicode=true&serverTimezone=Asia/Seoul"
    username: picplz
    password: picplz
  jpa:
    properties:
      hibernate:
        storage_engine: innodb
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    show_sql: true

  data:
    redis:
      host: redis
      port: 6379
      password: picplz

  session:
    store-type: redis

  main:
    lazy-initialization: true

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://picplz-db.cveay68wqy5c.ap-northeast-2.rds.amazonaws.com:3306/picplz
    username: picplz
    password: vlrvmfwm18!
  jpa:
    properties:
      hibernate:
        storage_engine: innodb
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    show_sql: true

  data:
    redis:
      host: redis
      port: 6379
      password: picplz

  session:
    store-type: redis

  main:
    lazy-initialization: true

---
spring:
  config:
    activate:
      on-profile: prod
